name: e_commerce_ui_project
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  iconsax: ^0.0.8
  intl: ^0.19.0
  http: ^1.2.0
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  flutter_native_splash: ^2.3.9
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    # Logos
    - assets/logos/
    # Icons
    - assets/icons/categories/
    - assets/icons/brands/
    - assets/icons/payment_methods/
    # Images
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/reviews/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800